### PR TITLE
Update invenio-cli version

### PR DESCRIPTION
**Pull request by tmorrell**

### CODE REVIEW

**Comment by ppanero** [comment]
Thanks a lot @tmorrell ! It bring me to think if we actually want to keep that sentence. As a person installing InvenioRDM does it bring you value? I think the latest is reflected in PyPi and then users are installing like `pip install invenio-cli` therefore there is not really a need to specify it in the docs?

My point is not to remove the version from the cli but just is mentioning (specific number) from the docs. Leaving something like:

```
invenio-cli --version

invenio-cli, version 0.11.

!!! note "CLI version"
     The CLI is in pre 1.0 release. You can find the latest version available in [PyPi](https://pypi.org/project/invenio-cli/)
```

@fenekku @zzacharo WDYT?

**Comment by zzacharo** [comment]
I think as we are still in a pre release and potentially this will changes often the upcoming months, I would say that we put in the docs a generic output of the command `invenio-cli --version` like `invenio-cli, version 0.x.`  and explain that x is the latest version that can be found on PyPi.

**Comment by fenekku** [comment]
Either way works for me. As long as we don't have to change it everytime :turtle:

**Comment by tmorrell** [comment]
I used the version number to check if I needed to update invenio-cli when going through the docs. But updating it every month seems annoying, and your linking text looks good.

I've incorporated your changes into this PR, but changed the link to the GitHub releases page. All the 1.0 series pre-releases show up on the top of the list on PyPi, which is a bit confusing. 

I used the GitHub editor to make the PR, but I just found the pencil and will be using it in the future!

**Pull request merged**
