### PR TITLE
Fix admin user account documentation

### PR DESCRIPTION
**Pull request by thomasms**
:heart: Thank you for your contribution!

### Description

Please describe briefly your pull request.

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by fenekku — COMMENTED** [review]
Thanks for your interest! Hmm, `administration-access` should be right. See https://github.com/inveniosoftware/invenio-administration/blob/main/invenio_administration/permissions.py . What issue did you encounter when using it? Maybe something else is off... admin-access is broader (too broad) so it will work, but is probably a security risk.

**Comment by thomasms** [comment]
For me `administration-access` didn't work, you can see my error message below.

```bash
[root@a5e314412111 src]# invenio access allow administration-access user admin@localhost.com
Traceback (most recent call last):
  File "/usr/bin/invenio", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1720, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1657, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/invenio_access/cli.py", line 147, in process_allow_action
    processor(action, argument)
  File "/usr/lib/python3.9/site-packages/invenio_access/cli.py", line 126, in processor
    db.session.add(ActionUsers.allow(action, argument=argument, user_id=user.id))
  File "/usr/lib/python3.9/site-packages/invenio_access/models.py", line 62, in allow
    return cls.create(action, exclude=False, **kwargs)
  File "/usr/lib/python3.9/site-packages/invenio_access/models.py", line 51, in create
    assert action.method == "action"
  File "/usr/lib/python3.9/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/usr/lib/python3.9/site-packages/werkzeug/local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
  File "/usr/lib/python3.9/site-packages/invenio_access/cli.py", line 31, in <lambda>
    return LocalProxy(lambda: f(ctx, param, value))
  File "/usr/lib/python3.9/site-packages/invenio_access/cli.py", line 51, in process_action
    raise click.BadParameter('Action "%s" is not registered.', value)
  File "/usr/lib/python3.9/site-packages/click/exceptions.py", line 111, in __init__
    super().__init__(message, ctx)
  File "/usr/lib/python3.9/site-packages/click/exceptions.py", line 61, in __init__
    self.cmd: t.Optional["Command"] = self.ctx.command if self.ctx else None
AttributeError: 'str' object has no attribute 'command'
```

I am running this using the container instance and following the instructions from [here](https://inveniordm.docs.cern.ch/install/).

I assumed it was a typo because it was the only thing that matched the access list:

```bash
[root@a5e314412111 src]# invenio access list
superuser-access:
admin-access:
files-rest-bucket-listmultiparts:*
files-rest-bucket-read:*
files-rest-bucket-read-versions:*
files-rest-bucket-update:*
files-rest-location-update:*
files-rest-multipart-delete:*
files-rest-multipart-read:*
files-rest-object-delete:*
files-rest-object-delete-version:*
files-rest-object-read:*
files-rest-object-read-version:*
```

**Comment by fenekku** [comment]
What version of invenio-app-rdm are you using? I am running 11.0.5 and I have:

```
> pipenv run invenio access list                                                                                                                                                              
Loading .env environment variables...                                                                                                                                                         
superuser-access:                                                                                                                                                                             
admin-access:                                                                                                                                                                                 
administration-access:                                                                                                                                                                        
files-rest-bucket-listmultiparts:*                                                                                                                                                            
files-rest-bucket-read:*                                                                                                                                                                      
files-rest-bucket-read-versions:*                                                                                                                                                             
files-rest-bucket-update:*                                                                                                                                                                    
files-rest-location-update:*                                                                                                                                                                  
files-rest-multipart-delete:*                                                                                                                                                                 
files-rest-multipart-read:*                                                                                                                                                                   
files-rest-object-delete:*                                                                                                                                                                    
files-rest-object-delete-version:*                                                                                                                                                            
files-rest-object-read:*                                                                                                                                                                      
files-rest-object-read-version:*                  
```
(the local/containerized divide "shouldn't" matter here)

If you are using v9 that would explain it :thinking:

**Comment by thomasms** [comment]
Ah indeed, I am using the LTS version 9.1. I assumed since this was the production version that the documentation would match, apologies for any confusion.

Is there a way to see the documentation for the LTS version easily?

**Comment by fenekku** [comment]
> Ah indeed, I am using the LTS version 9.1. I assumed since this was the production version that the documentation would match, apologies for any confusion.
> 
> Is there a way to see the documentation for the LTS version easily?

No worries, it's on us to have a better documentation versioning experience. There isn't a way to switch to documentation for another version currently (the docs are not versioned that way anyway). We've adhoc-ly added itatlicized "New in version X" text in some places, but clearly it's not systematic enough to cover all cases. Anyway, adding that disclaimer (`"New in version 11"`) is probably the right fix for now.

Thanks for pointing this out though! best.

**Comment by thomasms** [comment]
Thanks for the clear and quick response. I'll close the PR.

**Pull request closed without merging**
