### PR TITLE
Adds translators-guide.

### PR DESCRIPTION
**Pull request by chriz-uniba**
Refs https://github.com/inveniosoftware/docs-invenio-rdm/issues/266

### CODE REVIEW

**Comment by chriz-uniba** [comment]
# To Ask / To Check

- how to contact the translation team? is there an email-alternative?
- does this discord-link work fine?
  68747470733a2f2f7061642e677764672e64652f75706c6f6164732f75706c6f61645f66343761376234386338336634306430346433336138663630373261336466322e706e67


- [list of modules to tanslate](https://github.com/inveniosoftware/invenio-i18n/issues/99) - does this list get a stable place to be? 
  - I would prefer to link to one place where this is always up to date and not copy paste and duplicate stuff, which leads nearly always to sync-issues.
- is there anything that needs to be done when a module is completely translated/reviewed?
- do we use this? https://docs.transifex.com/localization-tips-workflows/plurals-and-genders#how-pluralized-strings-are-handled-by-transifex
- anything still missing from that
  - workflow from discord: So the workflow is: I check a sentence, if I'm happy I set the status 'reviewed', if I'm unhappy I fix it and set/leave the 'unreviewed', if I'm unhappy and don't know how to fix I comment/unreview/... depending on the problem.
- upper/lower case on title/headlines (not consistent in whole docu?)

**Comment by mb-wali** [comment]
@chriz-uniba I have tried to answer some of your questions on top:

* The discord ĺink should work fine for now.
* ignore adding the list of modules.
* once the module is completely translated - in order that the user should see the translations. there should be a new release of the module/package with newly added translations.
* yes we do use **tm-&-pluralized-strings**. 
tm-&-pluralized-strings

Please take a look at this link [Getting Started as a Translator](https://docs.transifex.com/getting-started-1/translators)

**Comment by chriz-uniba** [comment]
@mb-wali 
I will
- [ ] fix the list of modules
- [ ] link/integrate the 'getting started as a translator'
- [ ] include a note on tm-&-pluralized-strings.

Wrt. "is there anything that needs to be done when a module is completely translated/reviewed?"
- Is there something a *translator/reviewer* has to do?
- I know that the maintainer of a translation group gets notified (if the settings allow it) when a module is 100% translated
- So the maintainer needs to act, but not the translator/reviewer.
- Of course the translator/reviewer could also ping the maintainer etc. but do we want that mentioned as standard behaviour in the documentation?

**Review by mb-wali — APPROVED** [review]
nicely done :+1:

**Pull request merged**
