### PR TITLE
names: add ORCiD public data sync

### PR DESCRIPTION
**Pull request by jrcastro2**
* closes https://github.com/inveniosoftware/invenio-vocabularies/issues/353

### CODE REVIEW

**Review by fenekku — APPROVED** [review]
LGTM. I'll let you merge/wait since not familiar with bigger picture of this: is this only available in v12? if so targeting `dev` branch is probably better. If valid for before v12, `master` is good and if `> 12`, then ... I guess we park it :smile:

**Comment by utnapischtim** [comment]
i think this is referring to https://github.com/inveniosoftware/invenio-vocabularies/pull/366. it is v13

That would mean it the flag for `_Introduced in v13_` should be set or?

**Comment by utnapischtim** [comment]
we should really discuss how we handle that sort of documentation. i think waiting until the next version will be released is not a good option. IMHO. it produce a lot more work afterwards.

**Comment by slint** [comment]
> we should really discuss how we handle that sort of documentation. i think waiting until the next version will be released is not a good option. IMHO. it produce a lot more work afterwards.

I fully agree, we should add a `_Introduced in v13_` in this case and just merge in `master`. I will be a bit chaotic, but I don't see another way that doesn't make it very difficult to maintain different versions of docs in sync.

**Comment by utnapischtim** [comment]
> 
> I fully agree, we should add a `_Introduced in v13_` in this case and just merge in `master`. I will be a bit chaotic, but I don't see another way that doesn't make it very difficult to maintain different versions of docs in sync.

good, but i think we should wait until dev and so v12 documentation has been merged. otherwise it would be little bit strange to see v13 documentation but no v12 documentation

**Comment by fenekku** [comment]
> > I fully agree, we should add a `_Introduced in v13_` in this case and just merge in `master`. I will be a bit chaotic, but I don't see another way that doesn't make it very difficult to maintain different versions of docs in sync.
> 
> good, but i think we should wait until dev and so v12 documentation has been merged. otherwise it would be little bit strange to see v13 documentation but no v12 documentation

Yup, that's what I meant by parking it. :car:

**Comment by ntarocco** [comment]
Normally, we merge to `master` only things that are in the current (v12) or previous versions.

Anything else for future version should:
- have the sub-header `Introduced in InvenioRDM v...`
- merged to `dev` branch

When realising a new InvenioRDM version, the `dev` branch should be merged to `master`

**Comment by ntarocco** [comment]
I have changed the target branch. However, `dev` might need rebase on top of `master`.
@jrcastro2 can you add the sub-header?

**Comment by jrcastro2** [comment]
> I have changed the target branch. However, `dev` might need rebase on top of `master`. @jrcastro2 can you add the sub-header?

Added.
image

**Pull request merged**
