### PR TITLE
Add warning in documentation for installing services

### PR DESCRIPTION
**Pull request by mfenner**
Add warning in documentation for installing services: make sure Postgres is not installed locally (and using port 5432) when installing the database service and using Postgres. Closes inveniosoftware/invenio-cli#266.

### CODE REVIEW

**Review by fenekku — COMMENTED** [review]
Thanks for the warning message and the markdown cleanups (automated I guess, and if so how?)! One of those changes doesn't show a list correctly. Once fixed I will merge.

**Comment by fenekku** [comment]
Sorry, the sublisting is still not correct:

image

**Comment by mfenner** [comment]
@fenekku thanks for catching this. I disabled the VS Code extension `markdownlint` that was interfering here, following slightly different rules (two instead of four spaces for indentation). The list now finally looks good to me.

**Comment by lnielsen** [comment]
Probably the easiest is just submit another PR. Sorry, my mistake I didn't catch it :-)

**Comment by mfenner** [comment]
My fault. New pull request here: https://github.com/inveniosoftware/docs-invenio-rdm/pull/242

**Pull request merged**
